### ISSUE TITLE
Settings.xml files are not saving

### ISSUE THREAD

**Issue by jayskee** [idolpx/script.idolpx.installer#2]
When updating builds, none of the settings.xml files are saving.

Not sure if this is related to the userdata.old folder not being renamed or the copying of the files themselves.

This is particularly problematic as not even the settings file for the installer itself is saving, meaning that the device ID is reset to the same ID as whatever I have set on my master build?

I have tested this on MacOS, PC & Android (NVIDIA Shield) and all have produced the same result.

Additionally, none of the Trakt/RD account settings are saving which is obviously also extremely problematic.

Can you please revise the code? Thanks in advance.

**Comment by pkntl** [comment]
Yes, it's most likely caused by the userdata.old not being renamed. I've observed this too. In my case on Windows, the renaming of the userdata folder to userdata.old isn't permitted because it is in use. 

To solve this i changed the folder rename to a folder duplicate:
`shutil.copytree(userdata, userdata+'.old')`.

Your settings should copy back over from the userdata.old folder.

**Comment by idolpx** [comment]
Are you using Windows 7 or 10?  I want to try to reproduce this.

**Comment by pkntl** [comment]
Windows 10 in my case. I'm running the non-Microsoft Store version.

**Comment by idolpx** [comment]
Path separator was adjusted to resolve this issue.
